name: 'Your name here'
description: 'Provide a description here'
author: 'antoninklopp'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/cs-to-ts.yml'
runs:
  using: 'node12'
  main: 'lib/main.js'
